# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Staging:Build:Deploy

on:
  push:
    branches:
      - Staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '23.x'

      - name: npm install and build
        run: |
          npm install
          npm run build
      
      - name: Make Upload Directory
        run: mkdir -p ./upload/

      - name: Zip Prod artifact for deployment
        run: |
          cd ./dist
          zip ./../upload/prod.zip ./* -r
          cd ..

      - name: Development Build
        env:
          NODE_ENV: development
        run: npm run build-only -- --mode=development --base="/dev/"

      - name: Zip Dev artifact for deployment
        run: |
          cd ./dist
          zip ./../upload/dev.zip ./* -r
          cd ..

      - name: Build Storybook
        env:
          NODE_ENV: production
        run: npm run build-storybook

      - name: Zip Storybook artifact for deployment
        run: |
          cd ./storybook-static
          zip ./../upload/storybook.zip ./* -r
          cd ..

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: Prod-Dev-Storybook
          path: ./upload/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: Prod-Dev-Storybook
      
      - name: Create release directory
        run: mkdir -p ./release

      - name: List Directories
        run: |
          ls ./

      - name: Unzip artifact for deployment
        run: |
          unzip ./prod.zip -d ./release/
          unzip ./dev.zip -d ./release/dev/
          unzip ./storybook.zip -d ./release/story
          
      - name: Add web.config for MIME type configuration for Storybook JSON
        run: |
          cat <<EOF > ./release/story/web.config
          <configuration>
            <system.webServer>
              <staticContent>
                <mimeMap fileExtension=".json" mimeType="application/json" />
              </staticContent>
            </system.webServer>
          </configuration>
          EOF

      - name: List Directories
        run: |
          ls ./release/
          ls ./release/dev/
          ls ./release/story/

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'vuetify-playground-staging'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_818AEBF5E7EE48E1A3798A55E0F4C2AF }}
          package: .
