name: Run Tests

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for running unit tests
  unit-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Install dependencies
      run: npm install

    - name: Run unit tests
      run: npm run test:unit -- --reporter=junit --outputFile=./reports/unit-test-results.xml

    - name: List reports directory contents (unit tests)
      run: ls -la ./reports

    - name: Publish unit test results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: Unit Test Results
        path: ./reports/unit-test-results.xml
        reporter: jest-junit

  # Job for running Cypress E2E tests
  e2e-tests:
    runs-on: ubuntu-latest
    needs: unit-tests  # Runs after unit tests

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '23'

    - name: Install dependencies
      run: npm install

    - name: Only Build Application
      run: npm run build-only

    - name: Run Preview Server
      run: npm run preview

    - name: Run Cypress E2E tests
      run: npm run test:e2e -- --reporter junit --reporter-options "mochaFile=./reports/e2e-test-results.xml,toConsole=true"

    - name: List reports directory contents (E2E tests)
      run: ls -la ./reports

    - name: Publish E2E test results
      if: always()
      uses: dorny/test-reporter@v1
      with:
        name: E2E Test Results
        path: ./reports/e2e-test-results.xml
        reporter: jest-junit
